from __future__ import annotations

from enum import StrEnum

from .schemas import SanitizedDecisionContext, StructuredExplanation


class FallbackReason(StrEnum):
    PROVIDER_NOT_CONFIGURED = "provider_not_configured"
    MISSING_API_KEY = "missing_api_key"
    PROVIDER_TIMEOUT = "provider_timeout"
    PROVIDER_RATE_LIMITED = "provider_rate_limited"
    PROVIDER_UNAVAILABLE = "provider_unavailable"
    INVALID_JSON = "invalid_json"
    SCHEMA_VALIDATION_FAILED = "schema_validation_failed"
    ACTION_MISMATCH = "action_mismatch"
    UNEXPECTED_PROVIDER_RESPONSE = "unexpected_provider_response"


def build_fallback(context: SanitizedDecisionContext, reason: FallbackReason) -> StructuredExplanation:
    selected = context.decision.selected_action
    selected_candidate = next(candidate for candidate in context.candidates if candidate.action == selected)
    key_factors = [
        {"factor": "expected net recovery value", "impact": "The selected action had the strongest permissible expected net value in the stored decision trace."}
    ]
    if context.decision_factors.cost_changed_winner:
        key_factors.append({"factor": "action cost", "impact": "Action cost changed the winner compared with the cost-free comparison."})
    if context.decision_factors.fatigue_changed_winner:
        key_factors.append({"factor": "customer fatigue", "impact": "The observable fatigue penalty changed the winner."})
    if context.decision_factors.constraint_changed_winner:
        key_factors.append({"factor": "policy constraint", "impact": "A deterministic constraint changed which action could win."})
    if context.decision_factors.tie_break_applied:
        key_factors.append({"factor": "deterministic tie-break", "impact": "A configured deterministic tie-break resolved a near tie."})
    alternatives = []
    for candidate in context.candidates:
        if candidate.action == selected:
            continue
        if candidate.status == "blocked":
            blocked_reason = candidate.blocked_reason if candidate.blocked_reason in {"outside_contact_window", "unavailable_action"} else "policy constraint"
            reason_text = f"Not selected because deterministic policy blocked it: {blocked_reason}."
        else:
            reason_text = "Not selected because its stored expected net value was lower than the selected action."
        alternatives.append({"action": candidate.action, "reason_not_selected": reason_text})
    if selected == "DO_NOTHING":
        summary = "No intervention was selected because the expected benefit of available recovery actions did not justify intervention costs and customer-contact penalties."
        next_step = "Monitor the case without initiating a recovery action."
    else:
        summary = f"{selected} was selected by the deterministic decision engine from the stored permissible candidates."
        next_step = f"Proceed with {selected} through the existing policy-validated execution path."
    if selected_candidate.status != "permissible":
        summary = "The stored decision requires review because its selected action is not marked permissible."
    return StructuredExplanation(
        summary=summary,
        recommendation={"action": selected, "reason": "The action was already selected by deterministic expected-value scoring and policy validation."},
        key_factors=key_factors,
        alternatives=alternatives,
        next_step=next_step,
        operator_note="This explanation was generated by the deterministic fallback and does not change the stored decision.",
        limitations=["This is an explanation of a stored decision, not a recovery guarantee."],
    )
