"use client";

import { formatAction, formatDate, formatPaise, formatPercent } from "../lib/formatters";
import type { RecoveryIntelligence } from "../lib/types";
import { ArrowRightIcon, CheckIcon, ChevronDownIcon, ClockIcon, ShieldIcon } from "./icons";
import { StatusBadge } from "./shell";

function humanize(value: string) {
  return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());
}

export function RecoveryIntelligenceNarrative({ intelligence }: { intelligence: RecoveryIntelligence }) {
  const decision = intelligence.decision;
  const selectedAction = decision?.selected_action ?? intelligence.intervention.action;
  return <section className="intelligence-narrative" aria-label="Case recovery intelligence">
    <div className="panel-heading"><div><span className="section-overline">Case intelligence</span><h2>One recovery story, from signal to outcome</h2></div><span className="panel-note">Observable evidence · persisted state</span></div>
    <div className="intelligence-stage-strip">{["DETECT", "DIAGNOSE", "DECIDE", "INTERVENE", "RECOVER", "LEARN"].map((stage) => <span className={intelligence.journey_summary.stages_completed.includes(stage) ? "complete" : stage === intelligence.journey_summary.current_stage ? "current" : ""} key={stage}>{stage}</span>)}</div>
    <div className="intelligence-lead"><div className="intelligence-lead-mark"><ShieldIcon size={22} /></div><div><span className="section-overline">Current readout</span><h3>{intelligence.detection.summary}</h3><p>{intelligence.diagnosis.statement}</p></div><StatusBadge status={intelligence.outcome.status} /></div>
    <div className="intelligence-grid">
      <article className="intelligence-block detection-block"><div className="intelligence-block-head"><span className="intelligence-index">01</span><div><span className="section-overline">Problem detected</span><h3>Payment failure</h3></div><StatusBadge status={intelligence.detection.severity} /></div><p>{intelligence.detection.summary}</p><div className="intelligence-facts"><div><span>Failure pattern</span><strong>{humanize(intelligence.detection.failure_reason)}</strong></div><div><span>Amount at risk</span><strong>{formatPaise(intelligence.detection.amount_at_risk_paise)}</strong></div><div><span>Payment method</span><strong>{humanize(intelligence.detection.payment_method)}</strong></div><div><span>Contact window</span><strong>{intelligence.detection.outbound_contact_eligible ? "Eligible for outbound" : "Outside configured window"}</strong></div></div></article>
      <article className="intelligence-block diagnosis-block"><div className="intelligence-block-head"><span className="intelligence-index">02</span><div><span className="section-overline">Root cause</span><h3>{humanize(intelligence.diagnosis.primary_cause)}</h3></div><span className="confidence-chip">{intelligence.diagnosis.confidence} confidence</span></div><p>{intelligence.diagnosis.statement}</p><details><summary>View evidence <ChevronDownIcon size={14} /></summary><div className="evidence-list">{intelligence.diagnosis.evidence.map((item) => <div key={`${item.field}-${item.value}`}><strong>{item.field}</strong><span>{item.value}</span><p>{item.interpretation}</p></div>)}</div></details></article>
      <article className="intelligence-block decision-block"><div className="intelligence-block-head"><span className="intelligence-index">03</span><div><span className="section-overline">CHIMERA decision</span><h3>{selectedAction ? formatAction(selectedAction) : "Decision pending"}</h3></div>{decision && <span className="stored-mark"><CheckIcon size={13} /> Stored</span>}</div><p>{decision?.decision_summary ?? "No deterministic decision has been persisted for this case yet."}</p>{decision && <><div className="decision-signals">{decision.cost_affected && <span>Cost changed winner</span>}{decision.fatigue_affected && <span>Fatigue changed winner</span>}{decision.constraint_affected && <span>Constraints changed winner</span>}{decision.highest_probability_action_differed && <span>Stored rules changed the winner</span>}</div><details><summary>Alternatives and constraints <ChevronDownIcon size={14} /></summary><div className="alternative-list">{decision.alternatives.map((item) => <div key={item.action}><div><strong>{formatAction(item.action)}</strong><StatusBadge status={item.status} /></div><span>{item.reason_not_selected}</span><small>{formatPercent(item.predicted_probability)} predicted recovery</small></div>)}</div></details></>}</article>
      <article className="intelligence-block intervention-block"><div className="intelligence-block-head"><span className="intelligence-index">04</span><div><span className="section-overline">Intervention</span><h3>{intelligence.intervention.action ? formatAction(intelligence.intervention.action) : "Not started"}</h3></div><StatusBadge status={intelligence.intervention.status} /></div><p>{intelligence.intervention.execution_summary}</p><div className="provider-line"><span>Provider mode</span><strong>{intelligence.intervention.provider_mode}</strong></div>{intelligence.intervention.voice && <div className="voice-intelligence"><div><strong>{intelligence.intervention.voice.label}</strong><StatusBadge status={intelligence.intervention.voice.status} /></div><p>{intelligence.intervention.voice.conversation_result}</p><small>{intelligence.intervention.voice.customer_intent ? `Customer intent: ${humanize(intelligence.intervention.voice.customer_intent)}` : "No customer intent recorded"}</small></div>}</article>
      <article className="intelligence-block outcome-block"><div className="intelligence-block-head"><span className="intelligence-index">05</span><div><span className="section-overline">Outcome</span><h3>{humanize(intelligence.outcome.status)}</h3></div><StatusBadge status={intelligence.outcome.status} /></div><p>{intelligence.outcome.summary}</p>{intelligence.outcome.recovered_amount_paise !== null && <div className="outcome-amount"><span>Recovered amount</span><strong>{formatPaise(intelligence.outcome.recovered_amount_paise)}</strong></div>}<div className="recovery-path">{intelligence.outcome.recovery_path.map((step, index) => <span key={`${step}-${index}`}><i>{index + 1}</i>{step}{index < intelligence.outcome.recovery_path.length - 1 && <ArrowRightIcon size={12} />}</span>)}</div></article>
    </div>
    {intelligence.explanation && <div className="stored-explanation"><ClockIcon size={15} /><span>Stored explanation · {intelligence.explanation.explanation_source} · {formatDate(intelligence.explanation.generated_at)}</span><strong>{intelligence.explanation.summary}</strong></div>}
    {intelligence.insights.length > 0 && <details className="learning-details"><summary><span><span className="section-overline">06 · Learn</span><strong>Operational insights from this case</strong></span><ChevronDownIcon size={15} /></summary><div className="insight-list">{intelligence.insights.map((insight) => <div key={`${insight.type}-${insight.message}`}><span>{humanize(insight.type)}</span><p>{insight.message}</p></div>)}</div></details>}
  </section>;
}
