from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]


@dataclass(frozen=True)
class AppSettings:
    database_url: str = "postgresql+psycopg://chimera:chimera@localhost:5432/chimera"
    api_environment: str = "development"
    model_artifact_path: Path = REPOSITORY_ROOT / "data/model_benchmark_v1/recovery_model_v2_interaction_lr.json"
    simulator_config_path: Path = REPOSITORY_ROOT / "backend/configs/simulator_v1.yaml"
    llm_provider: str = "none"
    llm_base_url: str = "https://api.openai.com/v1"
    llm_api_key: str | None = None
    llm_model: str = "gpt-4o-mini"
    llm_timeout_seconds: float = 10.0
    voice_provider: str = "local"
    voice_enabled: bool = False
    voice_base_url: str | None = None
    voice_api_key: str | None = None
    voice_agent_id: str | None = None
    voice_phone_number: str | None = None
    voice_timeout_seconds: float = 10.0
    voice_mode: str | None = None
    voice_public_base_url: str | None = None
    voice_language: str = "hi-IN"
    exotel_api_key: str | None = None
    exotel_api_token: str | None = None
    exotel_account_sid: str | None = None
    exotel_flow_url: str | None = None
    exotel_caller_id: str | None = None
    exotel_api_base_url: str = "https://api.in.exotel.com"
    exotel_webhook_secret: str | None = None
    sarvam_enabled: bool = False
    sarvam_api_key: str | None = None
    sarvam_base_url: str = "https://api.sarvam.ai"
    sarvam_language_code: str = "hi-IN"
    sarvam_stt_model: str = "saaras:v3"
    sarvam_stt_mode: str = "codemix"
    sarvam_tts_model: str = "bulbul:v3"
    sarvam_tts_speaker: str = "shubh"
    sarvam_timeout_seconds: float = 20.0
    sarvam_mode: str | None = None
    payment_provider: str = "local"
    payment_enabled: bool = True
    razorpay_key_id: str | None = None
    razorpay_key_secret: str | None = None
    razorpay_webhook_secret: str | None = None
    razorpay_mode: str | None = None
    payment_timeout_seconds: float = 10.0
    payment_mode: str | None = None
    messaging_provider: str = "local"
    messaging_enabled: bool = True
    twilio_account_sid: str | None = None
    twilio_auth_token: str | None = None
    twilio_from_number: str | None = None
    twilio_to_number: str | None = None
    messaging_channel: str = "sms"
    twilio_whatsapp_from_number: str | None = None
    twilio_whatsapp_to_number: str | None = None
    twilio_whatsapp_content_sid: str | None = None
    messaging_public_base_url: str | None = None
    whatsapp_enabled: bool = False
    whatsapp_access_token: str | None = None
    whatsapp_phone_number_id: str | None = None
    whatsapp_to_number: str | None = None
    whatsapp_verify_token: str | None = None
    whatsapp_app_secret: str | None = None
    whatsapp_template_name: str | None = None
    whatsapp_template_language: str = "en_US"
    whatsapp_api_version: str = "v23.0"
    whatsapp_mode: str | None = None
    messaging_timeout_seconds: float = 10.0
    messaging_mode: str | None = None
    escalation_provider: str = "local"
    escalation_enabled: bool = True
    telegram_bot_token: str | None = None
    telegram_chat_id: str | None = None
    escalation_timeout_seconds: float = 10.0
    escalation_mode: str | None = None
    retry_provider: str = "local"
    retry_mode: str | None = None
    allow_live_execution: bool = False


def load_settings() -> AppSettings:
    return AppSettings(
        database_url=os.getenv("DATABASE_URL", AppSettings.database_url),
        api_environment=os.getenv("API_ENVIRONMENT", "development"),
        model_artifact_path=Path(os.getenv("MODEL_ARTIFACT_PATH", str(AppSettings.model_artifact_path))),
        simulator_config_path=Path(os.getenv("SIMULATOR_CONFIG_PATH", str(AppSettings.simulator_config_path))),
        llm_provider=os.getenv("LLM_PROVIDER", "none"),
        llm_base_url=os.getenv("LLM_BASE_URL", "https://api.openai.com/v1"),
        llm_api_key=os.getenv("LLM_API_KEY") or None,
        llm_model=os.getenv("LLM_MODEL", "gpt-4o-mini"),
        llm_timeout_seconds=float(os.getenv("LLM_TIMEOUT_SECONDS", "10")),
        voice_provider=os.getenv("VOICE_PROVIDER", "local"),
        voice_enabled=os.getenv("VOICE_ENABLED", "false").casefold() in {"1", "true", "yes"},
        voice_base_url=os.getenv("VOICE_BASE_URL") or None,
        voice_api_key=os.getenv("VOICE_API_KEY") or None,
        voice_agent_id=os.getenv("VOICE_AGENT_ID") or None,
        voice_phone_number=os.getenv("VOICE_PHONE_NUMBER") or None,
        voice_timeout_seconds=float(os.getenv("VOICE_TIMEOUT_SECONDS", "10")),
        voice_mode=os.getenv("VOICE_MODE") or None,
        voice_public_base_url=os.getenv("VOICE_PUBLIC_BASE_URL") or None,
        voice_language=os.getenv("VOICE_LANGUAGE", "hi-IN"),
        exotel_api_key=os.getenv("EXOTEL_API_KEY") or None,
        exotel_api_token=os.getenv("EXOTEL_API_TOKEN") or None,
        exotel_account_sid=os.getenv("EXOTEL_ACCOUNT_SID") or None,
        exotel_flow_url=os.getenv("EXOTEL_FLOW_URL") or None,
        exotel_caller_id=os.getenv("EXOTEL_CALLER_ID") or None,
        exotel_api_base_url=os.getenv("EXOTEL_API_BASE_URL", "https://api.in.exotel.com").rstrip("/"),
        exotel_webhook_secret=os.getenv("EXOTEL_WEBHOOK_SECRET") or None,
        sarvam_enabled=os.getenv("SARVAM_ENABLED", "false").casefold() in {"1", "true", "yes"},
        sarvam_api_key=os.getenv("SARVAM_API_KEY") or None,
        sarvam_base_url=os.getenv("SARVAM_BASE_URL", "https://api.sarvam.ai"),
        sarvam_language_code=os.getenv("SARVAM_LANGUAGE_CODE", "hi-IN"),
        sarvam_stt_model=os.getenv("SARVAM_STT_MODEL", "saaras:v3"),
        sarvam_stt_mode=os.getenv("SARVAM_STT_MODE", "codemix"),
        sarvam_tts_model=os.getenv("SARVAM_TTS_MODEL", "bulbul:v3"),
        sarvam_tts_speaker=os.getenv("SARVAM_TTS_SPEAKER", "shubh"),
        sarvam_timeout_seconds=float(os.getenv("SARVAM_TIMEOUT_SECONDS", "20")),
        sarvam_mode=os.getenv("SARVAM_MODE") or None,
        payment_provider=os.getenv("PAYMENT_PROVIDER", "local"),
        payment_enabled=os.getenv("PAYMENT_ENABLED", "true").casefold() in {"1", "true", "yes"},
        razorpay_key_id=os.getenv("RAZORPAY_KEY_ID") or None,
        razorpay_key_secret=os.getenv("RAZORPAY_KEY_SECRET") or None,
        razorpay_webhook_secret=os.getenv("RAZORPAY_WEBHOOK_SECRET") or None,
        razorpay_mode=os.getenv("RAZORPAY_MODE") or os.getenv("PAYMENT_MODE") or None,
        payment_timeout_seconds=float(os.getenv("PAYMENT_TIMEOUT_SECONDS", "10")),
        payment_mode=os.getenv("PAYMENT_MODE") or None,
        messaging_provider=os.getenv("MESSAGING_PROVIDER", "local"),
        messaging_enabled=os.getenv("MESSAGING_ENABLED", "true").casefold() in {"1", "true", "yes"},
        twilio_account_sid=os.getenv("TWILIO_ACCOUNT_SID") or None,
        twilio_auth_token=os.getenv("TWILIO_AUTH_TOKEN") or None,
        twilio_from_number=os.getenv("TWILIO_FROM_NUMBER") or None,
        twilio_to_number=os.getenv("TWILIO_TO_NUMBER") or None,
        messaging_channel=os.getenv("MESSAGING_CHANNEL", "sms").casefold(),
        twilio_whatsapp_from_number=os.getenv("TWILIO_WHATSAPP_FROM_NUMBER") or None,
        twilio_whatsapp_to_number=os.getenv("TWILIO_WHATSAPP_TO_NUMBER") or None,
        twilio_whatsapp_content_sid=os.getenv("TWILIO_WHATSAPP_CONTENT_SID") or None,
        messaging_public_base_url=os.getenv("MESSAGING_PUBLIC_BASE_URL") or None,
        whatsapp_enabled=os.getenv("WHATSAPP_ENABLED", "false").casefold() in {"1", "true", "yes"},
        whatsapp_access_token=os.getenv("WHATSAPP_ACCESS_TOKEN") or None,
        whatsapp_phone_number_id=os.getenv("WHATSAPP_PHONE_NUMBER_ID") or None,
        whatsapp_to_number=os.getenv("WHATSAPP_TO_NUMBER") or None,
        whatsapp_verify_token=os.getenv("WHATSAPP_VERIFY_TOKEN") or None,
        whatsapp_app_secret=os.getenv("WHATSAPP_APP_SECRET") or None,
        whatsapp_template_name=os.getenv("WHATSAPP_TEMPLATE_NAME") or None,
        whatsapp_template_language=os.getenv("WHATSAPP_TEMPLATE_LANGUAGE", "en_US"),
        whatsapp_api_version=os.getenv("WHATSAPP_API_VERSION", "v23.0"),
        whatsapp_mode=os.getenv("WHATSAPP_MODE") or None,
        messaging_timeout_seconds=float(os.getenv("MESSAGING_TIMEOUT_SECONDS", "10")),
        messaging_mode=os.getenv("MESSAGING_MODE") or None,
        escalation_provider=os.getenv("ESCALATION_PROVIDER", "local"),
        escalation_enabled=os.getenv("ESCALATION_ENABLED", "true").casefold() in {"1", "true", "yes"},
        telegram_bot_token=os.getenv("TELEGRAM_BOT_TOKEN") or None,
        telegram_chat_id=os.getenv("TELEGRAM_CHAT_ID") or None,
        escalation_timeout_seconds=float(os.getenv("ESCALATION_TIMEOUT_SECONDS", "10")),
        escalation_mode=os.getenv("ESCALATION_MODE") or None,
        retry_provider=os.getenv("RETRY_PROVIDER", "local"),
        retry_mode=os.getenv("RETRY_MODE") or None,
        allow_live_execution=os.getenv("CHIMERA_ALLOW_LIVE_EXECUTION", "false").casefold() in {"1", "true", "yes"},
    )
